# Generated by Django 4.2.4 on 2025-05-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commodity',
            new_name='CommodityPrice',
        ),
    ]
